# Generated by Django 5.1.1 on 2024-09-13 13:20

from django.db import migrations

from transactions.models import TransactionCategory


def populate_transaction_categories(apps, schema_editor):
    [
        t.save()
        for t in [
            TransactionCategory(id=1, name="SUPER_MARKET"),
            TransactionCategory(id=2, name="RENT"),
            TransactionCategory(id=3, name="WATER_BILL"),
            TransactionCategory(id=4, name="POWER_BILL"),
            TransactionCategory(id=5, name="INTERNET_BILL"),
            TransactionCategory(id=6, name="PHONE_BILL"),
            TransactionCategory(id=7, name="PAYROLL"),
            TransactionCategory(id=8, name="BOOKS"),
            TransactionCategory(id=9, name="HOBBIES"),
            TransactionCategory(id=10, name="CASH_WITHDRAWAL"),
            TransactionCategory(id=11, name="OTHER"),
        ]
    ]


def delete_transaction_categories(apps, schema_editor):
    for t in TransactionCategory.objects.filter(
        id__in={1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11}
    ):
        t.delete()


class Migration(migrations.Migration):
    dependencies = [
        ("transactions", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(
            populate_transaction_categories, delete_transaction_categories
        )
    ]
