# Generated by Django 5.1.1 on 2024-09-13 14:55

from django.db import migrations


from transactions.models import TransactionCategory


def add_transaction_category(apps, schema_editor):
    TransactionCategory(id=12, name="HOUSE_FACILITIES_BILL").save()


def delete_transaction_category(apps, schema_editor):
    t = TransactionCategory.find(12)
    t.delete() if t is not None else ...


class Migration(migrations.Migration):
    dependencies = [
        ("transactions", "0002_populate_transaction_categories_20240913_0820"),
    ]

    operations = [
        migrations.RunPython(add_transaction_category, delete_transaction_category)
    ]
